@startuml Contingent

EduProgramProfileFormYear "1" o-- "0..1" Contingent

class Contingent {
    AvgAdmScore: decimal?
    AdmittedFB: int?
    AdmittedRB: int?
    AdmittedMB: int?
    AdmittedBC: int?
    ..
    ActualFB: int?
    ActualRB: int?
    ActualMB: int?
    ActualBC: int?
    ..
    VacantFB: int?
    VacantRB: int?
    VacantMB: int?
    VacantBC: int?
    ..
    MovedIn: int?
    MovedOut: int?
    Restored: int?
    Expelled: int?
}

@enduml
