@startuml Contingent (variant 1)

EduProgramProfileFormYear "1" -- "0..*" ContingentRecord
ContingentRecord "0..*" -- "1" ContingentRecordType
ContingentRecord "0..*" -- "0..1" FinanceSourceType

class EduProgramProfileFormYear {
}

class ContingentRecord {
    Value: decimal
}

enum FinanceSourceType {
    FederalBudget
    RegionalBudget
    MunicipalBudget
    ByContract
}

enum ContingentRecordType {
    VaryByFinanceSource: bool
    OneYear: bool
    IsSystem: bool
    IsDecimal: bool
    --
    MovedIn
    MovedOut
    Restored
    Expelled
    Admitted
    Actual
    Vacant
    AvgAdmScore
}

@enduml

@startuml Contingent (variant 2)

EduProgramProfileFormYear "1" o-- "0..1" Contingent

class Contingent {
    AvgAdmScore: decimal?
    AdmittedFB: int?
    AdmittedRB: int?
    AdmittedMB: int?
    AdmittedBC: int?
    ..
    ActualFB: int?
    ActualRB: int?
    ActualMB: int?
    ActualBC: int?
    ..
    VacantFB: int?
    VacantRB: int?
    VacantMB: int?
    VacantBC: int?
    ..
    MovedIn: int?
    MovedOut: int?
    Restored: int?
    Expelled: int?
}

@enduml
