@startuml Volume of educational program

EduProgram <|-- EduProgramProfile

EduProgramProfile "0..*" -- "0..*" EduForm
(EduProgramProfile, EduForm) .. EduProgramProfileForm

EduProgramProfileForm "0..*" -- "0..*" Year
(EduProgramProfileForm, Year) .. EduProgramProfileFormYear

class EduProgramProfile {
    IsAdopted: bool
    Elearning: string
}
 
class Year {
    Year: string/int
    AdmissionIsOpen: bool
}

class EduProgramProfileForm {
    TimeToLearnMonths: int
    TimeToLearnHours: int
}

class EduProgramProfileFormYear {
    VolumeCU: int
    TrainingPracticeCU: int
    IndustrialPracticeCU: int
    UndergraduatePracticeCU: int
    ..
    StartDate: DateTime?
    EndDate: DateTime?
}

note right: CU - credit unit

@enduml
