@startuml Volume of educational program

EduProgramProfileFormYear "1..*" -- "1" EduProgramProfile
EduProgramProfileFormYear "0..*" -- "1" EduForm
EduProgramProfileFormYear "0..*" -- "1" Year
EduProgramProfileFormYear "1" -- "0..*" Discipline
Discipline "0..*" -- "0..1" DisciplineType

EduProgramProfileFormYear "1" -- "0..*" ContingentRecord

class EduProgramProfile {
    IsAdopted: bool
    Elearning: string
}

class Year {
    Year: int
    AdmissionIsOpen: bool
}

class EduProgramProfileFormYear {
    TimeToLearnMonths: int
    TimeToLearnHours: int
    ..
    StartDate: DateTime?
    EndDate: DateTime?
}

class Discipline {
    Code: string
    Title: string
    Hours: int
    DocumentUrl: string
}

enum DisciplineType {
    TrainingPractice
    IndustrialPractice
    UndergraduatePractice
}

@enduml
