@startuml Volume of educational program

EduProgramProfileFormYear "1..*" -- "1" EduProgramProfile
EduProgramProfileFormYear "0..*" -- "1" EduForm
EduProgramProfileFormYear "0..*" -- "1" Year
EduProgramProfileFormYear "1" .. "0..*" Discipline
Discipline "0..*" .. "0..1" DisciplineType

EduProgramProfileFormYear "1" -- "0..1" Contingent
EduProgramProfileFormYear "1" -- "0..1" EduVolume

class EduProgramProfile {
    IsAdopted: bool
    Elearning: string
}

class EduVolume {
    TimeToLearnMonths: int
    TimeToLearnHours: int
    Volume1Cu: int?
    Volume2Cu: int?
    Volume3Cu: int?
    Volume4Cu: int?
    Volume5Cu: int?
    VolumePractice1Cu: int?
    VolumePractice2Cu: int?
    VolumePractice3Cu: int?
}

class Year {
    Year: int
    AdmissionIsOpen: bool
}

class EduProgramProfileFormYear {
    StartDate: DateTime?
    EndDate: DateTime?
}

class Discipline {
    Code: string
    Title: string
    Hours: int
    DocumentUrl: string
}

enum DisciplineType {
    TrainingPractice
    IndustrialPractice
    UndergraduatePractice
}

@enduml
