@startuml Science Information for Edu. Program

EduProgram "1" o-- "0..1" Science

class Science {
    Directions: string
    Base: string
    ..
    Scientists: int?
    Students: int?
    Monographs: int?
    Articles: int?
    ArticlesForeign: int?
    Patents: int?
    PatentsForeign: int?
    Certificates: int?
    CertificatesForeign: int?
    ..
    FinancingByScientist: decimal?
}

@enduml